import logging
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import smtplib
from typing import Optional

logger = logging.getLogger(__name__)


class EmailService:
    """Service for sending emails with attachments."""

    def __init__(
        self,
        smtp_host: str,
        smtp_port: int,
        sender_email: str,
        sender_password: str,
        use_tls: bool = True,
    ):
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.sender_email = sender_email
        self.sender_password = sender_password
        self.use_tls = use_tls

    def send_report(
        self,
        recipient_email: str,
        report_title: str,
        report_content: bytes,
        format: str = "pdf",
    ) -> bool:
        """
        Send a report via email.

        Args:
            recipient_email: Email address to send to
            report_title: Title of the report
            report_content: Binary content of the report file
            format: File format ('pdf' or 'docx')

        Returns:
            True if sent successfully, False otherwise
        """
        try:
            # Create message
            msg = MIMEMultipart()
            msg["From"] = self.sender_email
            msg["To"] = recipient_email
            msg["Subject"] = f"Report: {report_title}"

            # Email body
            body = f"""
            <html>
              <body style="font-family: Arial, sans-serif; color: #333;">
                <h2 style="color: #2563eb;">Your Research Report</h2>
                <p>Hi,</p>
                <p>Your report <strong>{report_title}</strong> has been generated and is attached.</p>
                <p>You can open this file with your preferred PDF/Word reader.</p>
                <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
                <p style="font-size: 12px; color: #6b7280;">
                  This report was generated by Craftgent AI Agent.
                </p>
              </body>
            </html>
            """
            msg.attach(MIMEText(body, "html"))

            # Attach report file
            file_extension = "pdf" if format == "pdf" else "docx"
            mime_type = "application/pdf" if format == "pdf" else "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

            part = MIMEApplication(report_content, _subtype=file_extension)
            part.add_header(
                "Content-Disposition",
                f"attachment",
                filename=f"report.{file_extension}",
            )
            msg.attach(part)

            # Send email
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                if self.use_tls:
                    server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)

            logger.info(f"Report email sent to {recipient_email}")
            return True

        except Exception as e:
            logger.error(f"Failed to send report email: {str(e)}")
            return False

    def send_batch_reports(
        self, recipient_emails: list[str], report_title: str, report_content: bytes, format: str = "pdf"
    ) -> dict[str, bool]:
        """Send report to multiple recipients."""
        results = {}
        for email in recipient_emails:
            results[email] = self.send_report(email, report_title, report_content, format)
        return results
