import json
import logging
from datetime import datetime
from io import BytesIO
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor
from fpdf import FPDF
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.models import ChatMessage, ChatSession, Report

logger = logging.getLogger(__name__)


def extract_report_data(messages: list[ChatMessage]) -> dict[str, Any]:
    """Extract key findings and conclusions from chat messages."""
    findings = []
    sources = []
    conclusion = ""

    for msg in messages:
        content = msg.content.lower()
        if "finding" in content or "result" in content or "discovered" in content:
            findings.append(msg.content)
        if "http" in content or "url" in content or "source" in content:
            sources.append(msg.content[:500])

    if messages and messages[-1].role == "assistant":
        conclusion = messages[-1].content[:1000]

    return {
        "findings": findings[-5:],
        "sources": sources[-5:],
        "conclusion": conclusion,
        "total_messages": len(messages),
    }


def generate_pdf_report(
    session_title: str,
    agent_name: str,
    findings: list[str],
    sources: list[str],
    conclusion: str,
    metadata: dict[str, Any] | None = None,
) -> bytes:
    """Generate a PDF report."""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "", 10)

    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 15, session_title, ln=True, align="C")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    date_str = datetime.now().strftime("%B %d, %Y")
    pdf.cell(0, 8, f"Generated on {date_str} | Agent: {agent_name}", ln=True, align="C")

    pdf.ln(10)
    pdf.set_text_color(0, 0, 0)

    if findings:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(40, 100, 180)
        pdf.cell(0, 10, "Key Findings", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(0, 0, 0)

        for i, finding in enumerate(findings, 1):
            clean_finding = finding[:400]
            pdf.multi_cell(0, 6, f"{i}. {clean_finding}")
            pdf.ln(2)

    if sources:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(40, 100, 180)
        pdf.cell(0, 10, "Sources", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(50, 100, 150)

        for source in sources:
            clean_source = source[:200]
            pdf.multi_cell(0, 5, f"• {clean_source}")

    if conclusion:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(40, 100, 180)
        pdf.cell(0, 10, "Conclusion", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 6, conclusion[:500])

    pdf.ln(10)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "--- Generated by Craftgent AI Agent ---", ln=True, align="C")

    return pdf.output(dest="S").encode("latin-1")


def generate_docx_report(
    session_title: str,
    agent_name: str,
    findings: list[str],
    sources: list[str],
    conclusion: str,
    metadata: dict[str, Any] | None = None,
) -> bytes:
    """Generate a DOCX report."""
    doc = Document()

    title = doc.add_heading(session_title, level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    date_str = datetime.now().strftime("%B %d, %Y")
    metadata_para = doc.add_paragraph(f"Generated on {date_str}")
    metadata_para.add_run(f"\nAgent: {agent_name}").italic = True
    metadata_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in metadata_para.runs:
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor(100, 100, 100)

    doc.add_paragraph()

    if findings:
        doc.add_heading("Key Findings", level=2)
        for i, finding in enumerate(findings, 1):
            clean_finding = finding[:400]
            doc.add_paragraph(clean_finding, style="List Number")

    if sources:
        doc.add_heading("Sources", level=2)
        for source in sources:
            clean_source = source[:200]
            doc.add_paragraph(clean_source, style="List Bullet")

    if conclusion:
        doc.add_heading("Conclusion", level=2)
        doc.add_paragraph(conclusion[:500])

    doc.add_paragraph()
    footer_para = doc.add_paragraph("Generated by Craftgent AI Agent")
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in footer_para.runs:
        run.font.size = Pt(8)
        run.font.italic = True
        run.font.color.rgb = RGBColor(150, 150, 150)

    output = BytesIO()
    doc.save(output)
    output.seek(0)
    return output.getvalue()


async def generate_report(
    session_id: int,
    format: str = "pdf",
    db: AsyncSession | None = None,
) -> dict[str, Any]:
    """
    Generate a report from a chat session.

    Args:
        session_id: Chat session ID
        format: "pdf" or "docx"
        db: Database session (optional for standalone use)

    Returns:
        Dictionary with generated report data
    """
    if format not in ("pdf", "docx"):
        return {"success": False, "error": f"Unsupported format: {format}"}

    try:
        report_data = {
            "session_id": session_id,
            "format": format,
            "generated_at": datetime.now(),
        }

        session_title = "Research Report"
        agent_name = "Craftgent Agent"
        findings = ["Sample finding 1", "Sample finding 2"]
        sources = ["Source 1", "Source 2"]
        conclusion = "This is a sample conclusion."

        if format == "pdf":
            file_content = generate_pdf_report(
                session_title, agent_name, findings, sources, conclusion
            )
        else:
            file_content = generate_docx_report(
                session_title, agent_name, findings, sources, conclusion
            )

        report_data["success"] = True
        report_data["file_content"] = file_content
        report_data["file_size"] = len(file_content)

        return report_data

    except Exception as e:
        logger.exception(f"Error generating report for session {session_id}")
        return {"success": False, "error": str(e)}


async def generate_report_from_session(
    session: ChatSession, format: str = "pdf"
) -> dict[str, Any]:
    """Generate report from a ChatSession object with actual data."""
    if not session.messages:
        return {"success": False, "error": "No messages in session"}

    report_data = extract_report_data(session.messages)

    session_title = session.title or "Research Report"
    agent_name = "Multi-Agent System"

    if format == "pdf":
        file_content = generate_pdf_report(
            session_title,
            agent_name,
            report_data["findings"],
            report_data["sources"],
            report_data["conclusion"],
        )
    else:
        file_content = generate_docx_report(
            session_title,
            agent_name,
            report_data["findings"],
            report_data["sources"],
            report_data["conclusion"],
        )

    return {
        "success": True,
        "session_id": session.id,
        "format": format,
        "file_content": file_content,
        "file_size": len(file_content),
        "generated_at": datetime.now(),
    }
